[tool.poetry]
name = "mimic3-nlp"
version = "0.1.0"
description = "Projeto de ciência de dados com MIMIC-III usando dados estruturados e texto clínico"
authors = ["Anderson Alves Schinaid <andersonschinaid@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

# Manipulação e análise de dados
pandas = "^2.2.2"
numpy = "^1.26"
scikit-learn = "^1.5"
scipy = "1.10.1"

# Conexão com banco de dados (PostgreSQL)
sqlalchemy = "^2.0"
psycopg2-binary = "^2.9"

# Visualização
matplotlib = "^3.8"
seaborn = "^0.13"
plotly = "^5.20"

# NLP (text preprocessing e embeddings)
nltk = "^3.8"
spacy = "^3.7.0"
scispacy = "^0.5.5"
spacy-transformers = { version = "^1.3.8", python = "<3.13" }

# Modelos pré-treinados (HuggingFace Transformers)
transformers = "^4.37"
datasets = "^2.19"
torch = "^2.3"
accelerate = "^0.30"

# Explainability
shap = "^0.45"


# NLP estruturado com tópicos
bertopic = "^0.17"
sentence-transformers = "^2.7"

# Logging e utilitários
tqdm = "^4.66"
rich = "^13.7"
loguru = "^0.7"

# Modelos de tempo e séries temporais
tsfresh = "^0.20"
statsmodels = "^0.14"

# Salvamento e serialização
joblib = "^1.4"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0"
ipykernel = "^6.29"
notebook = "^7.2"
black = "^24.4"
isort = "^5.13"
flake8 = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
